import "./globals.css";
import { Rubik } from "next/font/google";
import type { Metadata } from "next";
import { Navbar } from "@/components/sections/Navbar";

const rubik = Rubik({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${rubik.className}`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
