import "./globals.css";
import { Rubik } from "next/font/google";
import {Rajdhani} from "next/font/google";
import type { Metadata } from "next";
import i18nConfig from "@/i18nConfig";
import { dir } from 'i18next';

const rubik = Rubik({ subsets: ["latin"] });
const rajdhani = Rajdhani({ subsets: ["latin"], weight: '700' });

export const metadata: Metadata = {
  title: "KV Maquinados",
  description: "Generated by create next app",
};

// Define the type for the params
interface Params {
  locale: string;
}

export function generateStaticParams(): Params[] {
  return i18nConfig.locales.map(locale => ({ locale }));
}

// Define the props type for RootLayout
interface RootLayoutProps {
  children: React.ReactNode;
  params: Params;
}

export default function RootLayout({ children, params: { locale } }: RootLayoutProps) {
  return (
    <html lang={locale} dir={dir(locale)}>
      <body className={rubik.className}>
        {children}
      </body>
    </html>
  );
}
